# Generated by Django 3.2.4 on 2021-06-19 14:10

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210618_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.TextField(max_length=16, null=True, unique=True, validators=[students.validators.phone_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, validators=[students.validators.email_validator]),
        ),
    ]
