# Generated by Django 3.2.4 on 2021-06-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.TextField(max_length=16, null=True, unique=True),
        ),
    ]
