# Generated by Django 3.2.4 on 2021-07-04 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
    ]
