# Generated by Django 3.2.4 on 2021-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210704_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
