# Generated by Django 3.2.4 on 2021-07-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=1500, null=True),
        ),
    ]
