# Generated by Django 3.2.4 on 2021-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start', models.DateField()),
                ('lessons_count', models.IntegerField(default=12)),
                ('lessons_passed', models.IntegerField(default=0)),
            ],
        ),
    ]
