# Generated by Django 3.2.4 on 2021-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_remove_teacher_group'),
        ('groups', '0005_auto_20210706_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(related_name='groups', to='teachers.Teacher'),
        ),
    ]
